# Generated by Django 5.2.4 on 2025-09-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_etudiant_adresse_etudiant_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='telephone',
        ),
    ]
