# Generated by Django 5.2.4 on 2025-09-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0003_remove_etudiant_adresse_remove_etudiant_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
