# Generated by Django 5.2.4 on 2025-10-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0005_etudiant_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='imageProfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
