# Generated by Django 5.2.4 on 2025-10-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0008_filiere_etudiant_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_document', models.CharField(choices=[('bulletin', 'Bulletin de notes'), ('certificat', 'Certificat'), ('diplome', 'Diplôme')], default='bulletin', max_length=20)),
                ('fichier', models.FileField(upload_to='bulletins/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.CharField(blank=True, max_length=20)),
                ('semestre', models.CharField(blank=True, max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.etudiant')),
            ],
        ),
    ]
